In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

In [2]:
n_rows = 365 * 24 
n_cols = 2         
cols = ['col1', 'col2'] 

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df.index = pd.date_range(start='2023-01-01', periods=n_rows, freq='h')

df.head()

                     col1  col2
2023-01-01 00:00:00     5     6
2023-01-01 01:00:00    17     4
2023-01-01 02:00:00     3    19
2023-01-01 03:00:00     3    15
2023-01-01 04:00:00     4    14

In [3]:
df.resample('M')['col1'].sum().to_frame()

C:\Users\ACER\AppData\Local\Temp\ipykernel_14964\985753190.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M')['col1'].sum().to_frame()

            col1
2023-01-31  7137
2023-02-28  6844
2023-03-31  7470
2023-04-30  7358
2023-05-31  7391
2023-06-30  7040
2023-07-31  7630
2023-08-31  7416
2023-09-30  7263
2023-10-31  7221
2023-11-30  7160
2023-12-31  7256

In [4]:
df.resample('D')['col1'].sum().to_frame()

            col1
2023-01-01   269
2023-01-02   200
2023-01-03   245
2023-01-04   272
2023-01-05   202
...          ...
2023-12-27   240
2023-12-28   221
2023-12-29   260
2023-12-30   222
2023-12-31   222

[365 rows x 1 columns]