In [ ]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

In [24]:
pd.DataFrame({'col1':[1, 2, 3, 4], 
              'col2':[5, 6, 7, 8]})

   col1  col2
0     1     5
1     2     6
2     3     7
3     4     8

In [25]:
n_rows = 5
n_cols = 3

arr = np.random.randint(1, 20, size=(n_rows, n_cols))
arr

array([[ 9,  9,  9],
       [16,  3, 13],
       [ 6,  6, 12],
       [16, 18,  1],
       [17,  2, 10]], dtype=int32)

In [26]:
pd.DataFrame(arr, columns=tuple('ABC'))

    A   B   C
0   9   9   9
1  16   3  13
2   6   6  12
3  16  18   1
4  17   2  10

In [22]:
r, c = 5, 4
columns = list('ABCD')
df = pd.DataFrame(np.random.randn(r, c), columns=columns)
print(df.head())

          A         B         C         D
0 -1.207741  0.360124  0.335594 -1.722137
1  0.015699 -1.380198 -1.095954  0.732176
2 -0.629084  0.619797  0.557586 -0.093876
3  1.830477 -0.185579  0.796351  0.257904
4  0.503287  0.573367  0.541513  0.077406

In [31]:
n_rows = 30 
n_cols = 4 
columns = list('ABCD')

data = np.random.randn(n_rows, n_cols)

df = pd.DataFrame(data, columns=columns)

print(df.head())

          A         B         C         D
0  0.035253 -0.696051 -1.241187  1.273192
1 -0.377831 -1.671494  0.507645  0.642483
2 -0.440247  1.209838 -0.128639  1.145837
3 -0.409083 -2.033040 -0.634442  0.356090
4 -1.171599 -0.767136 -0.865823 -0.716947

In [32]:
n_rows = 5 

data = {
    'A': np.random.randn(n_rows),                 
    'B': np.arange(1, n_rows + 1),                
    'C': pd.date_range('2024-01-01', periods=n_rows), 
    'D': ['foo', 'bar', 'baz', 'qux', 'quux']    
}

df = pd.DataFrame(data)

print(df.head())

          A  B          C     D
0  1.404487  1 2024-01-01   foo
1 -1.135085  2 2024-01-02   bar
2  0.059449  3 2024-01-03   baz
3  0.957777  4 2024-01-04   qux
4  0.960183  5 2024-01-05  quux

In [33]:
n_rows = 30  
n_cols = 4   
columns = list('ABCD')  

time_index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')  

df = pd.DataFrame(np.random.randn(n_rows, n_cols), index=time_index, columns=columns)

print(df.head())

                   A         B         C         D
2024-01-01 -0.967445  1.177023 -0.119055  0.599506
2024-01-02  1.297657  0.599732  0.452886 -0.423813
2024-01-03  0.234086 -0.792900 -1.509685 -0.264946
2024-01-04 -0.733754 -0.673425  0.083565  0.054898
2024-01-05 -0.515111 -0.473406  0.176481  0.493919

In [34]:
n_rows = 5
n_cols = 4

data = np.random.randn(n_rows, n_cols)

df = pd.DataFrame(data, columns=list('ABCD'))

df.iloc[0, 1] = np.nan
df.iloc[2, 3] = np.nan
df.iloc[4, 0] = np.nan

print(df.head())

          A         B         C         D
0 -0.364567       NaN  1.738065  0.547711
1  0.226423  1.201038  1.423351  0.024289
2 -2.022403  0.920224 -0.191643       NaN
3 -0.926325 -0.876154 -1.282628 -0.013686
4       NaN -0.850234  0.216741  0.571052