In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

In [3]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
df.groupby('species')['petal_length'].count().to_frame()

            petal_length
species
setosa                50
versicolor            50
virginica             50

In [6]:
df.groupby('species')['petal_length'].mean().to_frame()

            petal_length
species
setosa             1.462
versicolor         4.260
virginica          5.552

In [7]:
df.groupby('species')['petal_length'].median().to_frame()

            petal_length
species
setosa              1.50
versicolor          4.35
virginica           5.55

In [8]:
df.groupby('species')['petal_length'].agg(['count', 'mean', 'median'])

            count   mean  median
species
setosa         50  1.462    1.50
versicolor     50  4.260    4.35
virginica      50  5.552    5.55

In [9]:
df.groupby('species')['petal_length'].describe()

            count   mean       std  min  25%   50%    75%  max
species
setosa       50.0  1.462  0.173664  1.0  1.4  1.50  1.575  1.9
versicolor   50.0  4.260  0.469911  3.0  4.0  4.35  4.600  5.1
virginica    50.0  5.552  0.551895  4.5  5.1  5.55  5.875  6.9